name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Deploy to Render 
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Added a colon here
        run: | 
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \  # Fixed the header syntax
          https://api.render.com/v1/services/<service-id>/deploys      